### ISSUE TITLE
not working this links

### ISSUE THREAD

**Issue by guiworldtv** [LITUATUI/M3UPT#16]
os links de documentários não estão a funcionar

**Comment by LITUATUI** [comment]
São links para o YouTube, por isso só funcionam no Kodi com o addon (YouTube](https://kodi.wiki/view/Add-on:YouTube) instalado.

**Comment by guiworldtv** [comment]
Estou a ver direto do kodi com o addon Youtube instalado e não funcionaste para mim
E também a cnn brasil não está a funcionar :(

**Comment by LITUATUI** [comment]
Tenho o Kodi 19.3 num PC Linux e numa TV Box Android e está tudo a funcionar. A CNN Brasil tem algumas paragens.

**Comment by guiworldtv** [comment]
A SIC está a funcionar onde estás? aqui no brasil este link não está a abrir, também as variantes da sic não funcionam daqui

**Comment by LITUATUI** [comment]
Os canais SIC só funcionam com IP de Portugal, no estrangeiro dá para ver com VPN.
