### ISSUE TITLE
Portugal channels are dead

### ISSUE THREAD

**Issue by spotanjo3** [LITUATUI/M3UPT#23]
I love your m3u8. Awesome. The problem is that they are some dead links:

RTP 1
RTP2
RTP3
RPT ACORES
RPT MEMORIA
RPT MADEIRA
RPT AFRICA
RTP INTERNACIONAL
SIC
SIC NOTICAS

**Comment by LITUATUI** [comment]
Hi.

All channels are working here. SIC channels only work with Portuguese IP, but you should be able to watch RTP channels even if living abroad.

Are you using Kodi with PVR IPTV Simple Client?

Can you watch RTP channels on the [official website](https://www.rtp.pt/play/direto/rtp1)?

**Comment by spotanjo3** [comment]
Hi! I am using Televizo for my ANDROID TV SONY BRAVIA and those list above just didn't work.

I don't liked RTP channels from the official website because they are simple free and limited.

**Comment by LITUATUI** [comment]
Check [notes](https://github.com/LITUATUI/M3UPT#-notes).

**Comment by LITUATUI** [comment]
> KODI don't allowed me to use remote to change channels like cable tv.

![Kodi-PVR](https://user-images.githubusercontent.com/49299328/164125422-4cb0bb20-8d94-4691-bcaa-42e73d73b32c.jpg)
