### ISSUE TITLE
Most channels dead at the moment

### ISSUE THREAD

**Issue by DarkIsTheNewLight** [LITUATUI/M3UPT#35]
Can’t watch RPT and most other channels

**Comment by LITUATUI** [comment]
All working channels in Kodi, OTT Navigator and ProgTV.

**Comment by DarkIsTheNewLight** [comment]
still on OTT Navigator RPT channels won’t work
![image](https://user-images.githubusercontent.com/72315300/224511023-664ec87a-82fd-43b5-aa44-cff71c9c2038.jpg)

**Comment by LITUATUI** [comment]
RTP blocked the old user-agent. Check again.

**Comment by DarkIsTheNewLight** [comment]
Still broken

**Comment by DarkIsTheNewLight** [comment]
It’s working on Tivimate not OTT

**Comment by LITUATUI** [comment]
Working in Kodi.

![Kodi-RTP2](https://user-images.githubusercontent.com/49299328/224511766-47dddee1-a910-46e0-8799-907cc459a6d7.jpg)
