### ISSUE TITLE
RTP Down

### ISSUE THREAD

**Issue by DarkIsTheNewLight** [LITUATUI/M3UPT#37]
i can watch on rpt.pt but i think the user agent got blocked again since i can’t watch on ott or kodi

**Comment by LITUATUI** [comment]
RTP 1 e RTP 2 também estão OFF no Perfect Player se usada a descodificação por hardware, mas funcionam com o descodificador nativo.

No OTT Navigator e no ProgTV estão OK.

**Comment by LITUATUI** [comment]
Problema resolvido no Kodi.
