### ISSUE TITLE
Sic Notícias stopped working

### ISSUE THREAD

**Issue by megamster** [LITUATUI/M3UPT#43]
SIC Notícias started giving a 403 error a couple days ago, it doesnt currently seem to work.

**Comment by BubbleBurst** [comment]
same here. Tried several iptv players, none work.

**Comment by openseabrus** [comment]
It's unavailable everywhere, even on SIC's websites. I'm guessing it's going to auto-fix itself when SIC addresses this.

**Comment by guardiaopt** [comment]
Talvez não fosse má ideia alguém alertar a SIC que o canal não funciona...

**Comment by LITUATUI** [comment]
A SIC Notícias agora precisa de um referrer para funcionar, nem todas as apps suportam isto.

É recomendado usar a [OTT Navigator](https://m3upt.com/ottnavigator) em Android.
