### ISSUE TITLE
RTP1 and RTP2 channels not working

### ISSUE THREAD

**Issue by mvrk69** [LITUATUI/M3UPT#51]
The provided url of the stream for those 2 channels doesn't work any more.

I tried with streamlink using RTP websites links and it works fine:

streamlink https://www.rtp.pt/play/direto/rtp1 best
[cli][info] Found matching plugin rtpplay for URL https://www.rtp.pt/play/direto/rtp1
[cli][info] Available streams: 640k (worst), 1300k, 2500k (best)
[cli][info] Opening stream: 2500k (hls)
[cli][info] Starting player: /usr/bin/vlc
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...

Probably other RTP channels are also not working.

**Comment by LITUATUI** [comment]
They are working fine here with Portuguese IP.

What player are you using and are you using a Portuguese IP?

**Comment by mvrk69** [comment]
Even with Portuguese IP (NordVPN) still doesn't work for RTP channels, though i now see seems some problem with curl on my ODROID-C4 CoreELEC:

odroidc4:~ # curl -A "Firefox" https://streaming-live-app.rtp.pt/liverepeater/smil:rtp1HD.smil/playlist.m3u8 -o playlist.m3u8
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   432  100   432    0     0   1771      0 --:--:-- --:--:-- --:--:--  1777

odroidc4:~ # cat playlist.m3u8

<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>429 Unknown Error</title>
  </head>
  <body>
    <h1>Error 429 Unknown Error</h1>
    <p>Unknown Error</p>
    <h3>Error 54113</h3>
    <p>Details: cache-lis1490057-LIS 1698397682 3949052015</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>



On my laptop with Fedora 37 works fine:

$ curl -A "Firefox" https://streaming-live-app.rtp.pt/liverepeater/smil:rtp1HD.smil/playlist.m3u8 -o playlist.m3u8
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   221  100   221    0     0    975      0 --:--:-- --:--:-- --:--:--   977

$ cat playlist.m3u8
#EXTM3U
#EXT-X-VERSION:5
#EXT-X-STREAM-INF:BANDWIDTH=2540000
chunklist_b2540000_slpor.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1290000
chunklist_b1290000_slpor.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=640000
chunklist_b640000_slpor.m3u8
