### ISSUE TITLE
SIC Notícias not available

### ISSUE THREAD

**Issue by sarahfoxes** [LITUATUI/M3UPT#53]
Hello LITUATION,

Thank you for your excellent work.

The SIC Notícias channel is not working.

Is it possible to use the stream available on https://sicnoticias.pt/direto/2023-09-22-SIC-Noticias-em-Direto-0143aad2 ?

Thank you,

**Comment by LITUATUI** [comment]
You need Portuguese IP for SIC Notícias.

**Comment by sarahfoxes** [comment]
I have a portuguese IP.

**Comment by LITUATUI** [comment]
This channel needs a http-referrer.

It's working on most players, but not on Kodi that requires a different config to use the http-referrer.

If I configure the list to work on Kodi, it stops working on other players like VLC.

**Comment by LITUATUI** [comment]
SIC Notícias is now working on Kodi too.
