### ISSUE TITLE
OTT Player error 504 invalid key on Euronews PT stream

### ISSUE THREAD

**Issue by Silvervyusly** [LITUATUI/M3UPT#57]
I'm getting this 504 error whenever I try to use the Portuguese Euronews, it's not that relevant for me, but my family sometimes likes to watch it. Is this fixable or just a temporary thing? I followed the docs and restored the backup.
![Screenshot_2024-01-27-13-24-33-314_appnovatica stbp](https://github.com/LITUATUI/M3UPT/assets/137199541/cccd847e-5e0a-4745-b10d-98718cc97dbf)

**Comment by LITUATUI** [comment]
Thanks for the heads up mate.
