### ISSUE TITLE
The RTP1, TVI, CNN Portugal, Euronews PT and ARTV channels are not working

### ISSUE THREAD

**Issue by sarahfoxes** [LITUATUI/M3UPT#60]
Hello LITUATION,

Thank you for your excellent work.

The RTP1, TVI, CNN Portugal, Euronews PT and ARTV channels are not working either on my SMART TV and on VLC.

Is it possible to solve this problem?

Thank you,

**Comment by LITUATUI** [comment]
Hi.

ARTV is currently offline, all other streams are working. TVI and CNN Portugal streams have temporary tokens, you need to update the playlist.
