### ISSUE TITLE
RTP1 e RTP2 não funcionam 

### ISSUE THREAD

**Issue by manuelpinto95** [LITUATUI/M3UPT#65]
Steps to Reproduce:

1. Faz load da lista m3u em qualquer leitor IPTV (testado em Kodi, XTREME player, Perfect IPTV)
2. Tenta ver a RTP1 
3. Tenta ver a RTP2

Testado com:
- VPN dentro de Portugal conectado a servidor PT
- Sem VPN dentro de Portugal

**Comment by Furtif** [comment]
> Steps to Reproduce:
> 
> 1. Faz load da lista m3u em qualquer leitor IPTV (testado em Kodi, XTREME player, Perfect IPTV)
> 2. Tenta ver a RTP1
> 3. Tenta ver a RTP2
> 
> Testado com:
> 
> * VPN dentro de Portugal conectado a servidor PT
> * Sem VPN dentro de Portugal

aqui com ip frances funciona !! os 2 rpt 1-2


![image](https://github.com/LITUATUI/M3UPT/assets/11375035/b4f85f7e-9d8a-478f-a376-2191be347459)

**Comment by LITUATUI** [comment]
RTP 1 and RTP 2 sometimes aren't available for online streaming due to copyright stuff. This is temporary.
