### ISSUE TITLE
Missing channels

### ISSUE THREAD

**Issue by spotanjo3** [LITUATUI/M3UPT#71]
TVA canal Televisão África (TVA)
RTP INTERNACIONAL
TVI INTERNACIONAL

Thats all.

**Comment by spotanjo3** [comment]
I am curious. Have you got the message ? Are you able to adding them or what ? Just wonder. ^_^

**Comment by LITUATUI** [comment]
RTP Internacional and TVI Internacional are already in the list.

**Comment by spotanjo3** [comment]
Oh ok. Will check. Thank you 

what about TVA canal Televisão África (TVA)?

**Comment by LITUATUI** [comment]
Can't find any public stream for TVA.

**Comment by spotanjo3** [comment]
![IMG_0810](https://github.com/LITUATUI/M3UPT/assets/16481778/d10cf5ef-485a-4a56-bb90-65d47b804b51)

**Comment by spotanjo3** [comment]
No its on my private meo server

**Comment by spotanjo3** [comment]
> RTP Internacional and TVI Internacional are already in the list.

Dont see tvi Inter on either nos or meo. All i see is TVI

and RTP 1-3 only for nos and meo.

**Comment by LITUATUI** [comment]
You should have said that you were talking about EPG and not streams.

https://github.com/LITUATUI/M3UPT/blob/main/EPG/epg-rytec-pt.xml.xz

https://github.com/LITUATUI/M3UPT/blob/main/EPG/epg-rytec-pt.xml.xz

By the way, you should use OTT Navigator app and add your server to it. It's much better than other IPTV players.

**Comment by spotanjo3** [comment]
Can I use this app on my sony tv android? Indont used mobile and android tv box.

**Comment by LITUATUI** [comment]
Yes, it's an Android app.

**Comment by spotanjo3** [comment]
One question: what wrong with TiviMate? I was told this is the best app

**Comment by spotanjo3** [comment]
> You should have said that you were talking about EPG and not streams.
> 
> https://github.com/LITUATUI/M3UPT/blob/main/EPG/epg-rytec-pt.xml.xz
> 
> https://github.com/LITUATUI/M3UPT/blob/main/EPG/epg-rytec-pt.xml.xz
> 
> By the way, you should use OTT Navigator app and add your server to it. It's much better than other IPTV players.

I did. No epgs was found. I change it to raw and nothing.

**Comment by spotanjo3** [comment]
Good morning. Hope everything is well with you. I am waiting for your two answered for my one question and one issue.

**Comment by LITUATUI** [comment]
The EPG works fine with the M3UPT list, it isn't aimed for private servers. Ask your provider for help.

**Comment by spotanjo3** [comment]
Your other epgs works fine. This link doesnt. It doesnt show up at all. I rename blob to raw. Either doesnt. Just need to add three more above to my epg channels. Thats why
