### ISSUE TITLE
MEO servers storage code somewhere ? Do you know? 

### ISSUE THREAD

**Issue by spotanjo3** [LITUATUI/M3UPT#73]
Hello. And good afternoon/good evening. Sorry that I am not sure which thread should be going to. My apology if this is wrong here.

I noticed there are different codes about MEO channels. For an example: SPORT TV 5

My meo streaming m3u8 showing that SPORT TV 5 and SPORT TV 4 are - LIVE$SPORTTV_GOLFE_HD (SPORT TV 5) and LIVE$SPORTTVLive_HD (SPORT TV 4)

Do you have an accurate meo streaming m3u8 code somewhere ? I cannot find one.

If I rename it to LIVE$SPORTTV5_HD and SPORTTV4_HD and it wont worked. So I have to leave them untouched follwing to MEO Server code unknown and its working ok. I dont mind because I liked them the way they are. So I knew that MEO server read it as SPORTTV_GOLFE_HD and SPORTTVLive_HD only as well as other channels also.

There are many channels I have are storage by MEO server different from yours. I prefer to leave it untouched. Yeah, EPG can read them fine through TIVIMate select by select each instead of rename them.

Anyway, I want to know what MEO SERVER storage code lists like this ? I am curious about it. Do you know? Sorry about my english.

**Comment by LITUATUI** [comment]
I don't understand what you want, sorry.

**Comment by spotanjo3** [comment]
Okay. I m looking for an accurate channels from MEO as I gave you an example as above.

**Comment by LITUATUI** [comment]
MEO channels are listed [here](https://github.com/LITUATUI/M3UPT/blob/main/EPG/meo.pt.channels.xml).

**Comment by spotanjo3** [comment]
Yeah. They are not the same as private
Meo server.

For an example: yours —->  sport tv 5 and 5 

my server show different: SPORTTV_GOLFE_HD (sport tv 5) and  SPORTTVLive_HD (Sport 4) 

do you meo server’s own name for the channels? Sorry about my english

**Comment by LITUATUI** [comment]
The EPG works fine with the M3UPT list, it isn't aimed for private servers. Ask your provider for help.

**Comment by spotanjo3** [comment]
No. Your epg works fine. I am just asking about MEO server over there that have different channel name .. just want to know if you know other channel names  under authentication names?
