### ISSUE TITLE
Manutenção da lista de rádios

### ISSUE THREAD

**Issue by slimpt** [LITUATUI/M3UPT#75]
Queria perguntar se era possível fazer a manutenção da lista de rádios pois maior parte delas deixou de funcionar do nada. Tenho preferência nestas:

- Vodafone.fm (o novo nome é batida.fm)
- Rfm
- Cidade fm
- Megahits
- m80

**Comment by LITUATUI** [comment]
If nobody creates a PR to fix this today, I'll fix it tomorrow.

**Comment by LITUATUI** [comment]
If someone wants to retrieve the new m3u8 urls, they can use m3u8 sniffers/detectors like these extensions for Chrome: 
- [Video m3u8 sniffer](https://chromewebstore.google.com/detail/video-m3u8-sniffer-find-h/akkncdpkjlfanomlnpmmolafofpnpjgn)
- [M3u8 finder and HLS player](https://chromewebstore.google.com/detail/m3u8-finder-and-hls-playe/gijhpnmjcpbddpedmmdihijogkkejfgj)

There are also similar extension for Firefox.
