### ISSUE TITLE
"semicolon expected" error inside epg-nos-pt.xml and epg-pt.xml

### ISSUE THREAD

**Issue by jssilva25** [LITUATUI/M3UPT#81]
Hello,

tv_grab_vodafone.pt that I've got from here a long time ago, ceased to work since a few days, showing an "API error", after a long and excellent service. I'm a NOS subscriber but the main channels are the same.

I use TVHeadEnd as a server installed on a Rpi running Kodi on LibreElec, to allow me to watch news recordings, that's all I want, around the house. The recordings are made on the home server using smb.

So, after looking around for a working grabber in vain, here included, I decided to try using your ready made epg files to be read by TVHeadEnd using the tv_grab_file provided. It exited with a syntax error.

So I opened the file epg-nos-pt.xml with Notepad++ and checked the XML syntax with XML Tools and the following error shows up on the first programme line:

```
<programme start="20240704004000 +0000" stop="20240704021000 +0000" channel="1Plus1International.ua"><title lang="en">SuperWife</title><image>https://mage.stream.nos.pt/v1/nostv_mage/Images?sourceUri=http://vip.pam.local.internal/PAM.Images/Store/17a6f1c9bde345bebd56d581d54837b0&profile=ott_1_452x340&client_id=xe1dgrShwdR1DVOKGmsj8Ut4QLlGyOFI</image></programme>

&profile=ott_1_452x340&
Esperava-se ponto e vírgula (my translation: semicolon expected)

```
epg-meo-pt.xml syntax check is ok, I think because doesn't have <image> element, inside which the error lies.

Tried to delete the <image> element entirely with xsltproc but it doesn't let me because it can't parse the file..

Can you help, please? Thank you once more for your work.

**Comment by LITUATUI** [comment]
Hi, yes the tv_grab_vodafone doesn't work. It's an outdated grabber from the XMLTV [project](https://github.com/XMLTV/xmltv/tree/master/grab/pt_vodafone).

You can use working grabbers for Portuguese providers (RTP, Meo and Nos) [here](https://github.com/iptv-org/epg/tree/master/sites). That's what I'm now using for the M3UPT playlist.

**Comment by jssilva25** [comment]
Obrigado for your lightning fast reply.

I'll try it and report here as a reference for future users.

**Comment by jssilva25** [comment]
It works, but only after suppressing the element <image></image> where the syntax error is. I used:
`sed 's/<image>[^>]*>//g' tv_guide_raw.xml > tv_guide.xml`

If you want to report this to upstream, please go ahead.
