### ISSUE TITLE
Epg nos

### ISSUE THREAD

**Issue by fcporta** [LITUATUI/M3UPT#82]
Boa tarde, 
A lista de epg da nos deixou de funcionar a uns 4 dias ?
https://github.com/LITUATUI/M3UPT/raw/main/EPG/epg-nos-pt.xml.gz

**Comment by LITUATUI** [comment]
Boa tarde.

Não percebo o problema, o link dá um ficheiro EPG válido.

**Comment by scoobypt** [comment]
Estou com o mesmo problema. Dá me este erro: "XML syntax error on line 164: invalid character entity &profile (no semicolon)"

**Comment by LITUATUI** [comment]
Qual é o leitor de IPTV que dá esse erro?

Eu uso diariamente o OTT Navigator para Android e nunca tive problemas com EPG.

**Comment by scoobypt** [comment]
Está me a dar no Threadfin. A muito tempo que uso este epg porque foi o único que achei que tem imagens na programação sempre funcionou bem no Threadfin, a partir de dia 1 deste mês começou a dar esse erro a ultima atualizacao sem erro foi dia 30 e a linha que aponta o erro é a primeira linha da programação creio que o erro é exatamente na tag de imagem que não sei o que se passou ou foi alterada, não sei, por essa razão a da MEO funciona não tem imagens.

**Comment by fcporta** [comment]
A mim da erro no televizo, iptv pro, tivimate tanto na box como no tablet, começou a dar erro a uma ou duas semanas atrás

**Comment by xppx99** [comment]
Confirmo o mesmo erro, também no threadfin.

**Comment by thomraider12** [comment]
Também tenho o mesmo problema. Apesar disso funciona no Kodi.

**Comment by LITUATUI** [comment]
Caso queiram experimentar outros ficheiros de EPG aqui ficam os links:

m3upt.com/epg
m3upt.com/epg-pt1 (Nos)
m3upt.com/epg-pt2 (Meo)
m3upt.com/epg-pt3 (Rytec)
m3upt.com/epg-pt4 (RTP)

**Comment by a21674** [comment]
O problema está no conteúdo da tag <image> a url não respeita os caracteres reservados da linguagem de marcação XML. Seria necessário fazer escape a esses caracteres, deixo abaixo um exemplo:

Tag original:
<image>https://mage.stream.nos.pt/v1/nostv_mage/Images?sourceUri=http://vip.pam.local.internal/PAM.Images/Store/a5175ee2629145bfbed1ee83334f7396&profile=ott_1_452x340&client_id=xe1dgrShwdR1DVOKGmsj8Ut4QLlGyOFI</image>

Tag 'escaped':
<image>https://mage.stream.nos.pt/v1/nostv_mage/Images?sourceUri=http://vip.pam.local.internal/PAM.Images/Store/a5175ee2629145bfbed1ee83334f7396&amp;profile=ott_1_452x340&amp;client_id=xe1dgrShwdR1DVOKGmsj8Ut4QLlGyOFI</image>

**Comment by thomraider12** [comment]
Tenho aqui uma print, com as epg's que funcionam ou não funcionam. As que dizem "* minutes ago: atualizado" funcionam, as que dizem "Erro ao carregar" são as que não dão.
![Screenshot_20240717_082543_IPTV](https://github.com/user-attachments/assets/b396fb35-a5e5-4676-8518-0497ca9673a5)

**Comment by RubenTeixeira** [comment]
Resolvido quando o autor do epg-grabber fizer merge -> https://github.com/freearhey/epg-grabber/pull/21

**Comment by scoobypt** [comment]
Para mim o problema permanece apesar do merge já ter sido feito.

**Comment by fcporta** [comment]
Bom dia, epg dos canais eleven não aparece na epg da meo

**Comment by scoobypt** [comment]
Para mim a questão do epg da NOS continua igual: XML syntax error on line 164: invalid character entity &profile (no semicolon)

**Comment by thomraider12** [comment]
> Para mim a questão do epg da NOS continua igual: XML syntax error on line 164: invalid character entity &profile (no semicolon)

A mim também.
