### ISSUE TITLE
Tentar m3u8 v+ tvi

### ISSUE THREAD

**Issue by RodriPTV** [LITUATUI/M3UPT#85]
Olà eu tento meter o v+ tvi En m3u8. Como faço ? Eu tentei isto :
(#!/bin/bash

cd M3U

# V+ TVI - update the stream URL of V+ TVI

sed -i "/live_vmais\/live_vmais/ c https://video-auth6.iol.pt/live_vmais/live_vmais/playlist.m3u8?wmsAuthSign=$(wget https://services.iol.pt/matrix?userId= -o /dev/null -O -)/" M3UPT.m3u)
pode me dizer se vai dar certo ?

**Comment by thomraider12** [comment]
Acho que não é preciso, sendo que o link da TVI Ficção ainda funciona perfeitamente.

**Comment by RodriPTV** [comment]
Mas se meter o link oficial "https://video-auth7.iol.pt/live_vmais/live_vmais/playlist.m3u8" não dá. O link tem token.

**Comment by RodriPTV** [comment]
E preciso porque o link é token. "https://video-auth6.iol.pt/live_vmais/live_vmais/playlist.m3u8"
