### ISSUE TITLE
403 - TVI

### ISSUE THREAD

**Issue by VIRUXE** [LITUATUI/M3UPT#88]
Estou a receber um código de erro 403 no canal da TVI.

Estou a utilizar o OTT Navigator, com as listas importadas do backup.
A lista m3upt está a ser actualizada a cada 60 minutos.

![20240820_000123.jpg](https://github.com/user-attachments/assets/c1862b46-c00b-4104-a60c-bcfe298554a5)

![20240820_000225.jpg](https://github.com/user-attachments/assets/9d9d003d-3d2d-4794-8ea8-7c8414569232)

**Comment by LITUATUI** [comment]
Experimente o código que criei hoje.

**Comment by VIRUXE** [comment]
Actualizarei este issue assim que experimentar. Obrigado.

**Comment by LITUATUI** [comment]
Posso fechar?

**Comment by VIRUXE** [comment]
Só consegui confirmar agora. Está a funcionar, sem mudar nada.
Obrigado.
