### ISSUE TITLE
EPGs que não a epg-pt não têm a V+TVI

### ISSUE THREAD

**Issue by thomraider12** [LITUATUI/M3UPT#89]
Acho que o título explica. 
Obrigado.

**Comment by LITUATUI** [comment]
Já criei os pull requests, só falta serem aprovados.

[PR 1](https://github.com/iptv-org/epg/pull/2418)

[PR 2](https://github.com/iptv-org/epg/pull/2419)

**Comment by thomraider12** [comment]
Muito obrigado. Não sabia como fazer pull requests então pedi-lhe porque já tinha feito.

**Comment by LITUATUI** [comment]
Posso fechar?

**Comment by thomraider12** [comment]
Obrigado. Agora é mesmo só esperar 😅
