### ISSUE TITLE
RTP Memória com falha de acesso

### ISSUE THREAD

**Issue by Luis-Lourenco** [LITUATUI/M3UPT#90]
Boas, 

Já uso algum tempo esta lista, os canais que mais costumo ver são a RTP2 e RTP memória,  e algumas praias antes de sair de casa. 

Acontece que a RTP memória falha em certos programas, é mesmo assim? 

Obrigado

**Comment by LITUATUI** [comment]
Sim, a RTP Memória às vezes fica com a emissão online desligada por direitos de transmissão.

**Comment by Luis-Lourenco** [comment]
Obrigado, já verifiquei que programa não tem direito de emissão on-line.
