### ISSUE TITLE
Dúvida/Problema com #KODIPROP

### ISSUE THREAD

**Issue by jamexcb** [LITUATUI/M3UPT#97]
Desde já muito obrigado e parabéns pela iniciativa.

Estou a tentar usar: 
https://github.com/Fredolx/open-tv

Ainda está no inicio e tem alguns bugs. Mas acho que tem potencial por ser baste leve, multiplataforma e open source.
Um problema que surgiu foi com #KODIPROP
Isto é algo especifico só para o KODI? 
É algo comum noutros m3u e os outros leitores ignoram? 

Mais uma vez obrigado

**Comment by LITUATUI** [comment]
Exacto, é algo específico para o Kodi que deve ser ignorado pelos outros leitores.

Para dúvidas deve ser usada a secção [Discussions](https://github.com/LITUATUI/M3UPT/discussions), a secção [Issues](https://github.com/LITUATUI/M3UPT/issues) é para reportar problemas.
